# 파일 경로: .github/workflows/test.yml

name: Simple CI Test

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, world! GitHub Actions is working!"